# Generated by Django 2.2 on 2019-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20190410_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='shirt_size',
            new_name='question_1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pent_size',
            new_name='question_2',
        ),
    ]
