# Generated by Django 2.2 on 2019-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20190411_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='question_10',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_4',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_5',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_6',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_7',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_8',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_9',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
