# Generated by Django 2.2 on 2019-04-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20190411_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='question_11',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_12',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_13',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_14',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_15',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_16',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_17',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_18',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_19',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_20',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_21',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_22',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_23',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_24',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_25',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_26',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_27',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_28',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_29',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_30',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='question_31',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
