# Generated by Django 2.2 on 2019-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20190410_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pent_size',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(max_length=60),
        ),
    ]
