# Generated by Django 2.2 on 2019-04-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20190412_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='question_3',
            field=models.CharField(default='NA', max_length=60),
        ),
    ]
